language: python
python:
 - "3.5"
 - "3.6"
install:
 - pip install --upgrade pip setuptools
 - pip install numpy cython
 - "pip install .[train,test]"
script:
 - pylint openpifpaf --disable=fixme
 - pytest -vv
